default: component.hpp component.cpp wire.hpp wire.cpp
	g++ -c component.cpp wire.cpp make_graph.cpp map_list.cpp map_signals.cpp
clean:
	rm -f out *.o
main:
	g++ -g -std=c++11 -o out component.cpp wire.cpp main.cpp make_graph.cpp map_list.cpp map_signals.cpp
main2:
	g++ -g -std=c++11 -o out component.cpp wire.cpp main2.cpp make_graph.cpp map_list.cpp map_signals.cpp
main3:
	g++ -g -std=c++11 -o out component.cpp wire.cpp main3.cpp make_graph.cpp map_list.cpp map_signals.cpp
